verbose: false
instrumentation:
  excludes: [
    'dist/**',
    'coverage/**',
    'server/helpers/**',
    'gulpfile.babel.js',
    'server/updates/**',
    'server/mailers/**',
    'config/cloudinary.js',
    'config/env/staging.js',
    'config/env/production.js',
    'server/services/Redis.js',
    'config/env/development.js',
  ]
  include-all-sources: true
reporting:
    print: summary
    reports:
        - lcov
    dir: ./coverage
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
check:
    global:
        statements: 50
        lines: 50
        branches: 50
        functions: 50
    each:
        statements: 50
        lines: 50
        branches: 50
        functions: 20
